### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x86-64-assembly#1]
Edit this issue to keep track of the tasks you're working on towards launch.

We have a rough guide for how to launch a track, which is sorely outdated but
quite possibly better than nothing (I'm so sorry, I'm waaaay behind on getting
documentation updated).
https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

Check out https://github.com/orgs/exercism/teams/track-maintainers/discussions/1
for details about the #maintainers channel in the exercism-team Slack workspace.

Please ask if you have any questions or if anything is confusing!

**Comment by kotp** [comment]
Should this repository be named x86_Assembly?  I think x86 is an architecture, while Assembly is the language, and while both are important, the first doesn't answer "What language are we practicing?"

**Comment by kytrinyx** [comment]
That would make sense to me. @bergjohan -- your call, I think!

**Comment by bergjohan** [comment]
@kytrinyx I agree with @kotp and I think we should make the change, but I think we should use all lowercase and dash instead of underscore to follow the naming convention of other exercism repositories. So the name would be x86-assembly.

**Comment by kytrinyx** [comment]
x86-assembly it is! Changing it now.

**Comment by bergjohan** [comment]
@kytrinyx Thanks! :) I got a few hits when searching for "x86" in the repository. Does anything else need to be updated to "x86-assembly"?

**Comment by kotp** [comment]
Thought of something else as well, when "assembly" is the immediately interesting part (such as mirrored by perl5/perl6) should Assembly as the language be first, while the architecture choice is second?  Not sure how the two flavors are normally referenced.

**Comment by bergjohan** [comment]
@kotp I understand what you mean, but I don't think I've ever seen it written that way. I think we should stick with the current name.

**Comment by kotp** [comment]
I think that is definitely fine, as the search on the site for "assem" will pull them both up.

**Comment by kytrinyx** [comment]
> Should we update the track id (config.json, .travis.yml), travis-ci (README.md) and the team name aswell for consistency?

D'oh, I was thinking "oh, this is easy because we're not yet integrated into the site" /facepalm.

Yes, we definitely want to update the config file, etc. Sorry about that.

**Comment by bergjohan** [comment]
@kytrinyx Hi, I saw you updated README.md in 
https://github.com/exercism/x86-assembly/commit/03e3fe708fdb53995c67d2e2ba5127b0affc14aa. You made a change to "x686-assembly.svg", should it really say "x686"?

**Comment by kytrinyx** [comment]
It shouldn't have an svg at all. I'm not sure what happened.

**Comment by kytrinyx** [comment]
No, that's a typo.

**Comment by bergjohan** [comment]
Okay, thank you for fixing it :)

**Comment by bergjohan** [comment]
Hi @kytrinyx,

Yesterday I read that macOS Mojave "is the final version of macOS to support 32-bit application software", https://en.wikipedia.org/wiki/MacOS_Mojave.
Based on that I think it's better to use 64-bit assembly for this track. This unfortunately means that we should rename the track again to reflect that.

There are a few different names used for 64-bit x86 assembly, x86-64, x64, x86_64, AMD64 and Intel 64. Searching around the most commonly used seems to be x86_64 and x86-64.

I suggest using either **x86_64-assembly**  or **x86-64_assembly** as the track name.

If you agree with me, would you mind updating the track repository, the team repository and Travis? Hopefully this will be for the last time, but I think it's better to get it right from the beginning than having to change it later.

**Comment by bergjohan** [comment]
Hi again @kytrinyx,

I merged a branch to master yesterday, which should have made the Travis CI build pass. It still shows "build failing" though, and the latest build seems to have run after your "Fix typo" commit. Do you know why no build was run after the merge to master?

**Comment by kytrinyx** [comment]
We don't use underscores in track names, so I would prefer `x86-64-assembly`. How does that sound?

**Comment by kytrinyx** [comment]
> Do you know why no build was run after the merge to master?

Ah, I wonder if builds only run for PRs right now, not for branches. We have a ton of repos and lots of activity, and when it runs for both PRs and branches we use double the amount of Travis resources, which means that everything takes twice as long.

I could switch to running for branches only, and not PRs, and see if that would help.

The other thing I can do is to enable the setting which says that a PR _must_ be up to date with master before merging.

**Comment by bergjohan** [comment]
> We don't use underscores in track names, so I would prefer x86-64-assembly. How does that sound?

@kytrinyx After thinking some more about this, I think **x64-assembly** would be a better name for this track, I think it looks a lot cleaner.

**Comment by bergjohan** [comment]
> Ah, I wonder if builds only run for PRs right now, not for branches. We have a ton of repos and lots of activity, and when it runs for both PRs and branches we use double the amount of Travis resources, which means that everything takes twice as long.
> 
> I could switch to running for branches only, and not PRs, and see if that would help.
> 
> The other thing I can do is to enable the setting which says that a PR must be up to date with master before merging.
> 

@kytrinyx Ah okay! Thanks, but you can leave it as it is. It's more interesting to know if the tests are passing on a PR :)

**Comment by kytrinyx** [comment]
> Alright, x86-64-assembly sounds good! :)

Cool, I'll change the repo name, and leave you to update the various files that need adjustment.

**Comment by bergjohan** [comment]
@kytrinyx Perfect, thank you! :) Do you change the name in Travis and the team name aswell?
