### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/x86-64-assembly#137]
This repository's `main` branch currently does not pass all CI checks.
This makes detecting issues in PRs harder and might result in a broken track, and so is an important thing to fix.

The following CI workflows are currently failing:

https://github.com/exercism/x86-64-assembly/runs/3370785355
https://github.com/exercism/x86-64-assembly/runs/3370785323
https://github.com/exercism/x86-64-assembly/runs/3370785285

## Tracking

https://github.com/exercism/v3-launch/issues/55

**Comment by sudhackar** [comment]
Fixed with #144 @ErikSchierboom
