### ISSUE TITLE
Potential cheese using libc

### ISSUE THREAD

**Issue by cafce25** [exercism/x86-64-assembly#151]
Because the tests are written in C the final binary has to be linked against libc, it is therefore possible to use C-functions like `bsearch` etc to 'solve' the exercises [see iteration 1 of my `binary-search` solutions](https://exercism.org/tracks/x86-64-assembly/exercises/binary-search/solutions/cafce25).

I'm not at all sure how this should be handled here is the ways I can think of:
- Just leave it as it is and accept that some might use it to ie implement binary-search exercise.
- Make it impossible to use extern libraries from assembler code (not sure how this could be implemented)
- Write additional tests that check against usage of libc functions (also not sure how to implement it)

**Comment by SleeplessByte** [comment]
In general, for _practice_ exercises, if people want to cheat, we let them cheat :). In the end you only have yourself with this.

**Comment by ErikSchierboom** [comment]
☝️ Unfortunately, it is not doable to prevent people from cheating (e.g. they could look up an example solution online anyway if they want to). So I'd also argue that: just let them cheat. They don't gain anything from it but that's their choice.

**Comment by kotp** [comment]
I am not even convinced it is "cheating" if it solves the problem.  Learning how to solve problems with the tools available, even if that solution is unexpected, gives experience in problem solving.  Hopefully it leads to also knowing when that is the better solution, why it may be sub-optimal, etc.

So "cheating" may not even be applicable here.  I do not believe that the OP suggested it was cheating though.  Only that a tooling that is provided, perhaps unintentionally, may be used to solve the problem outside of what might be the expected bounds of the exercise.

**Comment by kotp** [comment]
I did find it interesting that the word _solve_ is quoted.  If it does not solve the problem, then the tests should indicate that through a failure reporting.  Otherwise it really is solving the problem presented.

**Comment by cafce25** [comment]
@kotp That's precisely the point the instructions state:
"Implement a binary search algorithm.", which my iteration 1 does not, it is merely using one already implemented in libc which then in turn would indicate missing tests.

That being said I agree with the overall sentiment of let everybody use whatever solution they can come up with.
To be honest hearing everyones opinion on this was my main motivation to raise this.

**Comment by kotp** [comment]
"implement" defined as "put to use".  If it said "write" then I would fully agree with that.  Yet, we understand that the intention is to write it yourself.  I bring this up during mentoring, while allowing that we have "put to use" what was needed to solve the problem.

Implement: "A means of achieving an end; an instrument"
