### ISSUE TITLE
All tests pass with no code submitted, in x86-64 Assembly - Triangle

### ISSUE THREAD

**Issue by TheRealOwenRees** [exercism/x86-64-assembly#164]
In the browser code editor, all tests pass if you do not submit any code. [This](https://exercism.org/tracks/x86-64-assembly/exercises/triangle/solutions/adep3zjh) user did just that and it has passed. 

I have not tested this with a CLI submission.

**Comment by sudhackar** [comment]
Nice catch!
I ported this exercise to the x86 track. I can see why this could happen - by calling convention the return(`al` in x86) isn't changed at all and could contain some value which could trigger this outcome.

**Comment by rdipardo** [comment]
> I have not tested this with a CLI submission.

An empty solution does *not* pass the tests locally, at least not in the following environment:

    glibc version: 2.36
    gcc (Debian 12.2.0-14) 12.2.0
    GNU Make 4.3

    $ make
    triangle_test.c:24:test_equilateral_triangle_all_sides_are_equal:FAIL: Expected TRUE Was FALSE
    triangle_test.c:138:test_equilateral_triangle_any_side_is_unequal:PASS
    triangle_test.c:139:test_equilateral_triangle_no_sides_are_equal:PASS
    triangle_test.c:140:test_equilateral_triangle_all_zero_sides_is_not_a_triangle:PASS
    triangle_test.c:48:test_equilateral_triangle_sides_may_be_floats:FAIL: Expected TRUE Was FALSE
    triangle_test.c:54:test_isosceles_triangle_last_two_sides_are_equal:FAIL: Expected TRUE Was FALSE
    triangle_test.c:60:test_isosceles_triangle_first_two_sides_are_equal:FAIL: Expected TRUE Was FALSE
    triangle_test.c:66:test_isosceles_triangle_first_and_last_sides_are_equal:FAIL: Expected TRUE Was FALSE
    triangle_test.c:72:test_isosceles_triangle_equilateral_triangles_are_also_isosceles:FAIL: Expected TRUE Was FALSE
    triangle_test.c:146:test_isosceles_triangle_no_sides_are_equal:PASS
    triangle_test.c:147:test_isosceles_triangle_first_triangle_inequality_violation:PASS
    triangle_test.c:148:test_isosceles_triangle_second_triangle_inequality_violation:PASS
    triangle_test.c:149:test_isosceles_triangle_third_triangle_inequality_violation:PASS
    triangle_test.c:102:test_isosceles_triangle_sides_may_be_floats:FAIL: Expected TRUE Was FALSE
    triangle_test.c:108:test_scalene_triangle_no_sides_are_equal:FAIL: Expected TRUE Was FALSE
    triangle_test.c:152:test_scalene_triangle_all_sides_are_equal:PASS
    triangle_test.c:153:test_scalene_triangle_two_sides_are_equal:PASS
    triangle_test.c:154:test_scalene_triangle_may_not_violate_triangle_inequality:PASS
    triangle_test.c:155:test_scalene_triangle_sides_may_be_floats:PASS

    -----------------------
    19 Tests 8 Failures 0 Ignored
    FAIL
    make: *** [Makefile:29: all] Error 8


The real problem is the test runner ignores the exit code of the `make` task: https://github.com/exercism/x86-64-assembly-test-runner/blob/2360f54b486d33974faa1dbe96b6811f7ea270c9/run.sh#L13

The shell only gets the exit code returned by the `python3` command. As long as it runs the script successfully (and it always will), the exit code is 0 *regardless* of what "results.out" actually contains. It's an easy enough oversight to make; the [Scheme track] is currently suffering from a similar one.

A simple fix would be storing the exit code of `stdbuf` (which is non-zero when a test fails). Then, *after* running the Python script, exit with whatever `stdbuf` returned, e.g.

~~~sh
stdbuf -oL make > "$3"results.out 2>&1
TEST_RESULT=$(echo $?)
python3 "${cwd}"/process_results.py "$3"results.out
exit $TEST_RESULT
~~~

[Scheme track]: https://github.com/exercism/scheme/pull/285

**Comment by rdipardo** [comment]
There's more going on here, but at least it's certain that the test runner is at fault.

First, the musl libc that ships with Alpine really does appear to be initializing the argument registers with phantom data as @sudhackar suggested. Adding a few debug messages to the runner's `run.sh` script reveals as much:

<details>
<summary>Alpine test runner output:</summary>
<pre>
<code>
$ ./docker-run.sh triangle ../exercism-x86-64-assembly/exercises/practice/triangle
[+] Building 17.5s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                             0.0s
 => => transferring dockerfile: 250B                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                0.0s
 => => transferring context: 113B                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/alpine:3.10                                                                                                   0.8s
 => [1/6] FROM docker.io/library/alpine:3.10@sha256:451eee8bedcb2f029756dc3e9d73bab0e7943c1ac55cff3a4861c52a0fdd3e98                                             0.8s
 => => resolve docker.io/library/alpine:3.10@sha256:451eee8bedcb2f029756dc3e9d73bab0e7943c1ac55cff3a4861c52a0fdd3e98                                             0.0s
 => => sha256:396c31837116ac290458afcb928f68b6cc1c7bdd6963fc72f52f365a2a89c1b5 2.80MB / 2.80MB                                                                   0.3s
 => => sha256:451eee8bedcb2f029756dc3e9d73bab0e7943c1ac55cff3a4861c52a0fdd3e98 1.64kB / 1.64kB                                                                   0.0s
 => => sha256:e515aad2ed234a5072c4d2ef86a1cb77d5bfe4b11aa865d9214875734c4eeb3c 528B / 528B                                                                       0.0s
 => => sha256:e7b300aee9f9bf3433d32bc9305bfdd22183beb59d933b48d77ab56ba53a197a 1.47kB / 1.47kB                                                                   0.0s
 => => extracting sha256:396c31837116ac290458afcb928f68b6cc1c7bdd6963fc72f52f365a2a89c1b5                                                                        0.3s
 => [internal] load build context                                                                                                                                0.0s
 => => transferring context: 780B                                                                                                                                0.0s
 => [2/6] RUN apk add --no-cache coreutils gcc libc-dev make nasm python3                                                                                        7.9s
 => [3/6] WORKDIR /opt/test-runner                                                                                                                               0.1s
 => [4/6] COPY run.sh bin/                                                                                                                                       0.1s
 => [5/6] COPY process_results.py ./                                                                                                                             0.1s
 => [6/6] COPY debug.asm ./                                                                                                                                      0.1s
 => exporting to image                                                                                                                                           7.6s
 => => exporting layers                                                                                                                                          7.6s
 => => writing image sha256:c9efdc690ab9ca82ab7e12f2475f118b3b9bd9e67b34e4866f17d51dfa423837                                                                     0.0s
 => => naming to docker.io/library/test-runner                                                                                                                   0.0s
Solution code:                                                                                                                                                        
section .text

global is_equilateral
is_equilateral:
    ; Provide your implementation here
    ret

global is_isosceles
is_isosceles:
    ; Provide your implementation here
    ret

global is_scalene
is_scalene:
    ; Provide your implementation here
    ret

%ifidn __OUTPUT_FORMAT__,elf64
section .note.GNU-stack noalloc noexec nowrite progbits
%endif

triangle_test.c:137:test_equilateral_triangle_all_sides_are_equal:PASS
triangle_test.c:138:test_equilateral_triangle_any_side_is_unequal:PASS
triangle_test.c:139:test_equilateral_triangle_no_sides_are_equal:PASS
triangle_test.c:140:test_equilateral_triangle_all_zero_sides_is_not_a_triangle:PASS
triangle_test.c:141:test_equilateral_triangle_sides_may_be_floats:PASS
triangle_test.c:142:test_isosceles_triangle_last_two_sides_are_equal:PASS
triangle_test.c:143:test_isosceles_triangle_first_two_sides_are_equal:PASS
triangle_test.c:144:test_isosceles_triangle_first_and_last_sides_are_equal:PASS
triangle_test.c:145:test_isosceles_triangle_equilateral_triangles_are_also_isosceles:PASS
triangle_test.c:146:test_isosceles_triangle_no_sides_are_equal:PASS
triangle_test.c:147:test_isosceles_triangle_first_triangle_inequality_violation:PASS
triangle_test.c:148:test_isosceles_triangle_second_triangle_inequality_violation:PASS
triangle_test.c:149:test_isosceles_triangle_third_triangle_inequality_violation:PASS
triangle_test.c:150:test_isosceles_triangle_sides_may_be_floats:PASS
triangle_test.c:151:test_scalene_triangle_no_sides_are_equal:PASS
triangle_test.c:152:test_scalene_triangle_all_sides_are_equal:PASS
triangle_test.c:153:test_scalene_triangle_two_sides_are_equal:PASS
triangle_test.c:154:test_scalene_triangle_may_not_violate_triangle_inequality:PASS
triangle_test.c:155:test_scalene_triangle_sides_may_be_floats:PASS

 - - - - - - - - - - -  - - 
19 Tests 0 Failures 0 Ignored 
OK
stdbuf -oL make > "$3"results.out 2>&1 exited with code 0
Finishing with code 0
</code>
</details>

Now, replace Alpine with a stock Debian base image, and suddenly the `debug.asm` library does not link anymore:

    /usr/bin/ld: warning: debug.o: missing .note.GNU-stack section implies executable stack
    /usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
    collect2: error: ld returned 1 exit status
    make: *** [Makefile:32: tests] Error 1

Add the boilerplate assembler directive to `debug.asm` as needed, and now the tests clearly fail on an empty solution. The exit code is still 0, so the last step would be revising the runner script as I recommended above:

<details>
<summary>Debian test runner output:</summary>
<pre>
<code>
$ bash docker-run.sh triangle ../exercism-x86-64-assembly/exercises/practice/triangle
[+] Building 0.5s (11/11) FINISHED
 => [internal] load .dockerignore                                                                                                                                0.0s
 => => transferring context: 113B                                                                                                                                0.0s
 => [internal] load build definition from Dockerfile                                                                                                             0.0s
 => => transferring dockerfile: 451B                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/debian:stable-slim                                                                                            0.3s
 => [1/6] FROM docker.io/library/debian:stable-slim@sha256:b09f68bffcf9c14f3105f262e92321d05abaf48460d1f43f884325bcd4395b95                                      0.0s
 => [internal] load build context                                                                                                                                0.0s
 => => transferring context: 4.29kB                                                                                                                              0.0s
 => CACHED [2/6] RUN apt update     && apt -qqy --no-install-recommends install         coreutils         gcc         libc-dev         make         nasm         0.0s
 => CACHED [3/6] WORKDIR /opt/test-runner                                                                                                                        0.0s
 => CACHED [4/6] COPY run.sh bin/                                                                                                                                0.0s
 => CACHED [5/6] COPY process_results.py ./                                                                                                                      0.0s
 => [6/6] COPY debug.asm ./                                                                                                                                      0.1s
 => exporting to image                                                                                                                                           0.1s
 => => exporting layers                                                                                                                                          0.0s
 => => writing image sha256:694e8c844dc66640846e344abeff35c54e64366a8a00cfe4a31222b7ff2c181e                                                                     0.0s
 => => naming to docker.io/library/test-runner                                                                                                                   0.0s
Solution code:
section .text

global is_equilateral
is_equilateral:
    ; Provide your implementation here
    ret

global is_isosceles
is_isosceles:
    ; Provide your implementation here
    ret

global is_scalene
is_scalene:
    ; Provide your implementation here
    ret

%ifidn __OUTPUT_FORMAT__,elf64
section .note.GNU-stack noalloc noexec nowrite progbits
%endif

triangle_test.c:24:test_equilateral_triangle_all_sides_are_equal:FAIL: Expected TRUE Was FALSE
triangle_test.c:138:test_equilateral_triangle_any_side_is_unequal:PASS
triangle_test.c:139:test_equilateral_triangle_no_sides_are_equal:PASS
triangle_test.c:140:test_equilateral_triangle_all_zero_sides_is_not_a_triangle:PASS
triangle_test.c:48:test_equilateral_triangle_sides_may_be_floats:FAIL: Expected TRUE Was FALSE
triangle_test.c:54:test_isosceles_triangle_last_two_sides_are_equal:FAIL: Expected TRUE Was FALSE
triangle_test.c:60:test_isosceles_triangle_first_two_sides_are_equal:FAIL: Expected TRUE Was FALSE
triangle_test.c:66:test_isosceles_triangle_first_and_last_sides_are_equal:FAIL: Expected TRUE Was FALSE
triangle_test.c:72:test_isosceles_triangle_equilateral_triangles_are_also_isosceles:FAIL: Expected TRUE Was FALSE
triangle_test.c:146:test_isosceles_triangle_no_sides_are_equal:PASS
triangle_test.c:147:test_isosceles_triangle_first_triangle_inequality_violation:PASS
triangle_test.c:148:test_isosceles_triangle_second_triangle_inequality_violation:PASS
triangle_test.c:149:test_isosceles_triangle_third_triangle_inequality_violation:PASS
triangle_test.c:102:test_isosceles_triangle_sides_may_be_floats:FAIL: Expected TRUE Was FALSE
triangle_test.c:108:test_scalene_triangle_no_sides_are_equal:FAIL: Expected TRUE Was FALSE
triangle_test.c:152:test_scalene_triangle_all_sides_are_equal:PASS
triangle_test.c:153:test_scalene_triangle_two_sides_are_equal:PASS
triangle_test.c:154:test_scalene_triangle_may_not_violate_triangle_inequality:PASS
triangle_test.c:155:test_scalene_triangle_sides_may_be_floats:PASS

-----------------------
19 Tests 8 Failures 0 Ignored
FAIL
make: *** [Makefile:29: all] Error 8
stdbuf -oL make > "$3"results.out 2>&1 exited with code 2
Finishing with code 0

</code>
</pre>
</details>

**Comment by rdipardo** [comment]
To be sure, the [test runner interface](https://exercism.org/docs/building/tooling/test-runners/interface) specifies that:

> • The runner must exit with an exit code of 0 if it has run successfully, regardless of the status of the tests.

So resolving this would be a matter of simply migrating the base image away from musl libc (and hence from Alpine).

**Comment by bergjohan** [comment]
I've had this issue before because of using `bool` as a return type. My fix last time was to switch to returning an `int` instead.
See https://github.com/exercism/x86-64-assembly/issues/69 and https://github.com/exercism/x86-64-assembly/pull/70

**Comment by rdipardo** [comment]
It seems an outdated version of GCC was the problem all along.

A Debian 10 image with only the standard-issue compiler behaves identically to Alpine 3.10 (the runner's current base image):

<details>
<summary>Debian (Buster) image output:</summary>
<pre>
<code>
$ docker-run.sh triangle ../exercism-x86-64-assembly/exercises/practice/triangle
[+] Building 0.8s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                             0.0s
 => => transferring dockerfile: 430B                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                0.0s
 => => transferring context: 113B                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/debian:buster-slim                                                                                            0.4s
 => [internal] load build context                                                                                                                                0.0s
 => => transferring context: 707B                                                                                                                                0.0s
 => [1/6] FROM docker.io/library/debian:buster-slim@sha256:738002a6e94e8629a0f869be8ea56519887979d5ed411486441981a8b16f2fc8                                      0.0s
 => CACHED [2/6] RUN apt update     && apt -qqy --no-install-recommends install         gcc         libc-dev         make         nasm         python3-minimal   0.0s
 => CACHED [3/6] WORKDIR /opt/test-runner                                                                                                                        0.0s
 => [4/6] COPY run.sh bin/                                                                                                                                       0.0s
 => [5/6] COPY process_results.py ./                                                                                                                             0.0s
 => [6/6] COPY debug.asm ./                                                                                                                                      0.0s
 => exporting to image                                                                                                                                           0.1s
 => => exporting layers                                                                                                                                          0.1s
 => => writing image sha256:8a393b11a87b18db6d913b0faf5d314c44fb7943821b29712536b26231432501                                                                     0.0s
 => => naming to docker.io/library/test-runner                                                                                                                   0.0s
Solution code:
section .text

global is_equilateral
is_equilateral:
    ; Provide your implementation here
    ret

global is_isosceles
is_isosceles:
    ; Provide your implementation here
    ret

global is_scalene
is_scalene:
    ; Provide your implementation here
    ret

%ifidn __OUTPUT_FORMAT__,elf64
section .note.GNU-stack noalloc noexec nowrite progbits
%endif-e

triangle_test.c:137:test_equilateral_triangle_all_sides_are_equal:PASS
triangle_test.c:138:test_equilateral_triangle_any_side_is_unequal:PASS
triangle_test.c:139:test_equilateral_triangle_no_sides_are_equal:PASS
triangle_test.c:140:test_equilateral_triangle_all_zero_sides_is_not_a_triangle:PASS
triangle_test.c:141:test_equilateral_triangle_sides_may_be_floats:PASS
triangle_test.c:142:test_isosceles_triangle_last_two_sides_are_equal:PASS
triangle_test.c:143:test_isosceles_triangle_first_two_sides_are_equal:PASS
triangle_test.c:144:test_isosceles_triangle_first_and_last_sides_are_equal:PASS
triangle_test.c:145:test_isosceles_triangle_equilateral_triangles_are_also_isosceles:PASS
triangle_test.c:146:test_isosceles_triangle_no_sides_are_equal:PASS
triangle_test.c:147:test_isosceles_triangle_first_triangle_inequality_violation:PASS
triangle_test.c:148:test_isosceles_triangle_second_triangle_inequality_violation:PASS
triangle_test.c:149:test_isosceles_triangle_third_triangle_inequality_violation:PASS
triangle_test.c:150:test_isosceles_triangle_sides_may_be_floats:PASS
triangle_test.c:151:test_scalene_triangle_no_sides_are_equal:PASS
triangle_test.c:152:test_scalene_triangle_all_sides_are_equal:PASS
triangle_test.c:153:test_scalene_triangle_two_sides_are_equal:PASS
triangle_test.c:154:test_scalene_triangle_may_not_violate_triangle_inequality:PASS
triangle_test.c:155:test_scalene_triangle_sides_may_be_floats:PASS

-----------------------
19 Tests 0 Failures 0 Ignored
OK

gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
</code>
</pre>
</details>

At least there's plenty of time to get this fixed before [Nybbly November].

[Nybbly November]: https://forum.exercism.org/t/planning-for-12in23-nibbly-november-assembly-languages/4334

**Comment by bergjohan** [comment]
Well, I don't think we should depend on codegen by a specific compiler version. It might break again on the next upgrade. I still think the best way is to change the return type to `int`.

**Comment by rdipardo** [comment]
For illustration, attached is the disassembled triangle test program, generated with `objdump -M intel -S tests`, after building with gcc 8.3 and then gcc 12.

- [tests.gcc.8.3.asm.txt](https://github.com/exercism/x86-64-assembly/files/11861097/tests.gcc.8.3.asm.txt)

- [tests.gcc.12.asm.txt](https://github.com/exercism/x86-64-assembly/files/11861098/tests.gcc.12.asm.txt)

The first major difference is the `.init` section. GCC 8.3 calls the initialization subroutines `frame_dummy` and `__do_global_ctors_aux`, while gcc 12 does not:

```sh-session
$ diff -b tests.gcc.8.3.asm.txt tests.gcc.12.asm.txt | head -n 12
2c2
< tests.gcc.8.3:     file format elf64-x86-64
---
> tests.gcc.12:     file format elf64-x86-64
9,12c9,10
<     1001:     e8 a5 01 00 00          call   11ab <frame_dummy>
<     1006:     e8 e7 2e 00 00          call   3ef2 <__do_global_ctors_aux>
<     100b:     58                      pop    rax
<     100c:     c3                      ret
---
>     1001:     58                      pop    rax
>     1002:     c3                      ret
```

The purpose of `frame_dummy` seems to be initializing RSI and RDI whenever the register frame at `rip+0x5e45` is not `NULL`:

~~~asm
00000000000011ab <frame_dummy>:
    11ab:	48 83 3d 45 5e 00 00 	cmp    QWORD PTR [rip+0x5e45],0x0        # 6ff8 <__register_frame_info>
    11b2:	00
    11b3:	74 18                	je     11cd <frame_dummy+0x22>
    11b5:	55                   	push   rbp
    11b6:	48 8d 35 a3 5e 00 00 	lea    rsi,[rip+0x5ea3]        # 7060 <object.6149>
    11bd:	48 8d 3d 4c 38 00 00 	lea    rdi,[rip+0x384c]        # 4a10 <__EH_FRAME_BEGIN__>
    11c4:	48 89 e5             	mov    rbp,rsp
    11c7:	e8 b4 fe ff ff       	call   1080 <__register_frame_info@plt>
    11cc:	5d                   	pop    rbp
    11cd:	e9 1b ff ff ff       	jmp    10ed <register_tm_clones>
~~~

This might be eliminated with optimization, but I think that would ultimately impoverish students' learning opportunities, at least for the ones using their PCs.
