### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by nathanchere** [exercism/x86-64-assembly#73]
I think it would be a good idea to include a .gitignore file with this track which at least covers this:

```
*.o
**/tests
```

I see other tracks having it in the common parent folder rather than in each exercise, it seems like a good place here too.

**Comment by bergjohan** [comment]
We've got a `.gitignore` file at the top level directory which should cover this, see [https://github.com/exercism/x86-64-assembly/blob/master/.gitignore](https://github.com/exercism/x86-64-assembly/blob/master/.gitignore). Does this not work for you?

**Comment by nathanchere** [comment]
OK, weird. When I pull the exercises for this track I'm not getting the .gitignore which is why I opened the ticket.  I'm not doing anything different to what I do for other tracks.

**Comment by bergjohan** [comment]
Are you talking about pulling the exercise using the Exercism CLI?

Could you give me an example of a track where you are getting the file?

When pulling an exercise, you are not getting a Git repository. What are you using the `.gitignore` file for?

**Comment by nathanchere** [comment]
Rust, Python, Javascript, Elixir, C#. 
Pulling all with CLI. 
Maybe I added them myself and it has been so long I forgot doing it?:/

**Comment by bergjohan** [comment]
@nathanchere You are right, Rust and Elixir seems to include the `.gitignore` file in the exercises, see [https://github.com/exercism/rust/tree/master/exercises/accumulate](https://github.com/exercism/rust/tree/master/exercises/accumulate) and [https://github.com/exercism/elixir/tree/master/exercises/accumulate](https://github.com/exercism/elixir/tree/master/exercises/accumulate).

I don't understand why this is needed though, would you mind explaining what you are using the file for?

**Comment by kotp** [comment]
@bergjohan the knee jerk reaction here is that students are using git for versioning their exercises locally, so it isn't a "need" as much as a convenience, I think, that those tracks are providing for the students.

**Comment by bergjohan** [comment]
Yeah alright, I guess we could add that. I'll reopen the issue!

**Comment by bergjohan** [comment]
Done! :)
